/*Template generated by PyCharm on Saturday (9/21/2024), 5:35 AM.
* Author: Kramstyles (USER)
* Filename: page.jsx
*/

const Post = () => {
    return (
        <div>
            <h1>[id]</h1>
        </div>
    );
};

export default Post