/*Template generated by PyCharm on Saturday (9/21/2024), 5:35 AM.
* Author: Kramstyles (USER)
* Filename: page.jsx
*/

import {Author, CommentForm, Comments, PostDetail, SideBar} from "@/components";

const Post = () => {
    return (
        <div className="container mx-auto px-10 mb-8">
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
                <div className="col-span-1 lg:col-span-8">
                    <PostDetail />
                    <Author />
                    <CommentForm />
                    <Comments />
                </div>
                <SideBar />
            </div>
        </div>
    );
};

export default Post