/*Template generated by google-clone on Wednesday (9/11/2024), 4:31 AM.
 * Author: Kramstyles (USER)
 * Filename: app/search/web/page.tsx
 */

import Link from "next/link";

const API_KEY = process.env["NEXT_PUBLIC_GOOGLE_API_KEY"];
const CONTEXT_KEY = process.env["NEXT_PUBLIC_GOOGLE_CONTEXT_KEY"];
interface ResultProps {
  kind: string;
  title: string;
  htmlTitle: string;
  link: string;
  displayLink: string;
  snippet: string;
  htmlSnippet: string;
  formattedUrl: string;
  htmlFormattedUrl: string;
}

interface searchParamsProps {
  searchParams: { searchTerm: string };
}

const page = async ({ searchParams: { searchTerm } }: searchParamsProps) => {
  const url = `https://www.googleapis.com/customsearch/v1?key=${API_KEY}&cx=${CONTEXT_KEY}&q=${searchTerm}`;
  console.log(url);
  const response = await fetch(url);
  // If an error occurs during fetch.
  if (!response.ok) throw new Error("Something went wrong");
  const data = await response.json();
  const results = data.items;

  // If search item is empty
  if (!results) {
    return (
      <div className="flex flex-col justify-center items-center pt-10">
        <h1 className="text-3xl mb-4">No results found for {searchTerm}</h1>
        <p className="text-lg">
          Please, try searching for something else.{" "}
          <Link href="/" className="text-blue-500">
            Home
          </Link>
        </p>
      </div>
    );
  }

  return (
    <div>
      {results &&
        results.map((result: ResultProps) => (
          <h1 key={result.link}>{result.title}</h1>
        ))}
    </div>
  );
};

export default page;
