/*Template generated by google-clone on Wednesday (9/11/2024), 4:31 AM.
* Author: Kramstyles (USER)
* Filename: app/search/web/page.tsx
*/

const page = () => {
    return (
        <div>
            <h1 className="text-red-500">Web Search Page</h1>
        </div>
    );
};

export default page