/*Template generated by codebucks-blog on Tuesday (9/17/2024), 10:12 AM.
 * Author: Kramstyles (USER)
 * Filename: components/index.tsx
 */

import Logo from "@/components/Header/Logo";
import Link from "next/link";

const Header = () => {
  return (
    <header className="w-full py-4 px-10 flex items-center justify-between">
      <Logo />
      <nav className="w-max py-3 px-8 border border-solid border-dark rounded-full font-medium capitalize flex
      items-center gap-x-3 fixed top-6 bg-light/50 backdrop-blur-sm right-1/2 translate-x-1/2">
        <Link href="/">Home</Link>
        <Link href="/about">About</Link>
        <Link href="/contact">Contact</Link>
        <button>T</button>
      </nav>
      <div>
          <a href="https://example.com/kramstyles">LinkedIn</a>
          <a href="https://example.com/kramstyles">LinkedIn</a>
          <a href="https://example.com/kramstyles">LinkedIn</a>
          <a href="https://example.com/kramstyles">LinkedIn</a>
      </div>
    </header>
  );
};

export default Header;
