/*Template generated by codebucks-blog on Tuesday (9/17/2024), 10:25 AM.
 * Author: Kramstyles (USER)
 * Filename: components/Header/Logo.tsx
 */
import Image from "next/image";
import Link from "next/link";
import ProfileImage from "@/public/images/profile-img.png";

const Logo = () => {
  return (
    <Link href={"/"} className="flex items-center text-dark gap-x-3">
      <div className="w-16 rounded-full overflow-hidden border border-solid border-dark">
        <Image
          src={ProfileImage}
          alt="Kramstyles"
          className="w-full h-auto rounded-full"
          priority
        />
      </div>
      <span className="font-bold text-xl">First Next Blog</span>
    </Link>
  );
};

export default Logo;
