/*Template generated by NextTSDamn on Thursday (8/29/2024), 2:15 PM.
* Author: Kramstyles (USER)
* Filename: next-ts-tutorial/app/about/page.tsx
*/

const About = () => {
    return (
        <div className="max-w-6xl mx-auto p-3 space-y-7">
            <h1 className="text-2xl font-medium text-amber-600">About</h1>
            <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                Accusamus assumenda cum eius in iure nulla perferendis quia
                suscipit vero voluptate! Accusantium at deleniti dignissimos,
                ducimus maiores perspiciatis ratione recusandae reiciendis?
            </div>
            <div>A asperiores consequatur culpa cum debitis distinctio et hic
                id, illum laudantium magnam mollitia numquam provident
                quisquam quo, rem rerum tempore veritatis vitae voluptatibus?
                Deserunt eligendi magnam perspiciatis ullam vero.
            </div>
            <div>Assumenda laudantium nemo reiciendis. Accusamus cum cumque
                illum itaque libero nemo perferendis temporibus unde. Ad
                architecto blanditiis inventore minima mollitia nulla quam
                quia quisquam. Debitis dolorum facere similique velit veniam?
            </div>
        </div>
    );
};

export default About