/*Template generated by NextTSDamn on Sunday (8/25/2024), 3:45 PM.
* Author: Kramstyles (USER)
* Filename: next-ts-tutorial/app/(fetch)/refresh/page.tsx
*/

import {revalidateTag} from "next/cache";
const RefreshPage = () => {
    revalidateTag("users");
    return (
        <div>
            <h1>To refresh the 'user' tags and not HIT cache. This is the on-demand revalidation. </h1>
        </div>
    );
};

export default RefreshPage