/*Template generated by NextTSDamn on Sunday (8/25/2024), 3:10 PM.
* Author: Kramstyles (USER)
* Filename: next-ts-tutorial/app/loading.tsx
*/

const loading = () => {
    return (
        <div className="flex justify-center h-96">
            <img src="spinner.svg" alt="loading..."/>
        </div>
    );
};

export default loading;