/*Template generated by NextTSDamn on Sunday (8/25/2024), 3:10 PM.
 * Author: Kramstyles (USER)
 * Filename: next-ts-tutorial/app/loading.tsx
 */

import Image from "next/image";

const loading = () => {
  return (
    <div className="flex justify-center h-96">
      <Image src={"spinner.svg"} alt={"Processing..."}
      width="300" height="300"/>
    </div>
  );
};

export default loading;
