/*Template generated by NextTSDamn on Sunday (8/25/2024), 3:10 PM.
* Author: Kramstyles (USER)
* Filename: next-ts-tutorial/app/loading.tsx
*/

const loading = () => {
    return (
        <div>
            <h1>loading. This page is loading</h1>
        </div>
    );
};

export default loading;