/*Template generated by NextTSDamn on Tuesday (8/27/2024), 9:04 AM.
 * Author: Kramstyles (USER)
 * Filename: next-ts-tutorial/app/Providers.tsx
 */

"use client";

import React, { ReactNode } from 'react';
import { ThemeProvider } from "next-themes";

interface ProviderProps {
    children: ReactNode
}

const Providers: React.FC<ProviderProps> = ({ children }) => {
  return (
    <ThemeProvider defaultTheme="system" attribute="class">
      <div>
          { children }
      </div>
    </ThemeProvider>
  );
};

export default Providers;
