/*Template generated by PyCharm on Saturday (9/21/2024), 6:28 AM.
 * Author: Kramstyles (USER)
 * Filename: Author.jsx
 */

import Image from "next/image";

const Author = ({ name, image }) => {
  return (
    <div className="text-center mt-20 mb-8 p-2 relative rounded-lg bg-white bg-opacity-20">
      <div className="absolute left-0 right-1/2 -top-8">
        <Image
          src={image}
          alt={name}
          height={100}
          width={100}
          className="align-middle rounded"
          unoptimized
        />
      </div>
      <h3 className="font-bold text-capitalize my-4 text-xl">{name}</h3>
    </div>
  );
};

export default Author;
