/*Template generated by PyCharm on Saturday (9/21/2024), 6:28 AM.
* Author: Kramstyles (USER)
* Filename: Author.jsx
*/

const Author = () => {
    return (
        <div>
            <h1>Author</h1>
        </div>
    );
};

export default Author