/*Template generated by PyCharm on Thursday (9/19/2024), 4:57 AM.
* Author: Kramstyles (USER)
* Filename: Categories.jsx
*/

const Categories = () => {
    return (
        <div>
            <h1>Categories</h1>
        </div>
    );
};

export default Categories