/*Template generated by PyCharm on Saturday (9/21/2024), 6:28 AM.
* Author: Kramstyles (USER)
* Filename: Comments.jsx
*/

const Comments = () => {
    return (
        <div>
            <h1>Comments</h1>
        </div>
    );
};

export default Comments