/*Template generated by PyCharm on Saturday (9/21/2024), 6:28 AM.
* Author: Kramstyles (USER)
* Filename: CommentForm.jsx
*/

const CommentForm = () => {
    return (
        <div>
            <h1>CommentForm</h1>
        </div>
    );
};

export default CommentForm