/*Template generated by PyCharm on Thursday (9/19/2024), 4:57 AM.
 * Author: Kramstyles (USER)
 * Filename: PostCard.jsx
 */

const PostCard = ({ post }) => {
  return (
    <div>
        {post.title}
        {post.excerpt}
    </div>
  );
};

export default PostCard;
