/*Template generated by PyCharm on Thursday (9/19/2024), 4:57 AM.
 * Author: Kramstyles (USER)
 * Filename: PostCard.jsx
 */

const PostCard = ({ post }) => {
  return (
    <div className="text-white border-b border-blue-500 mb-5">
        <p className="font-semibold text-2xl">{post.title.rendered}</p>
        {post.excerpt.rendered}
    </div>
  );
};

export default PostCard;
