/*Template generated by PyCharm on Saturday (9/21/2024), 6:27 AM.
 * Author: Kramstyles (USER)
 * Filename: PostDetail.jsx
 */

import Parser from "html-react-parser";
import Image from "next/image";
import { CalenderSVG } from "@/icons";
import moment from "moment/moment";

export default async function PostDetail({ post }) {
  const yoast = post.yoast_head_json;
  const imgInfo = yoast.og_image[0];
  return (
    <div className="bg-white shadow-lg rounded-lg lg:p-8 pb-12 mb-8">
      <div className="relative overflow-hidden shadow-md mb-6">
        <Image
          src={imgInfo.url}
          alt={Parser(post.title.rendered)}
          priority
          width={imgInfo.width}
          height={imgInfo.height}
          className="object-top h-full w-full rounded-t-lg"
        />
      </div>
      <div className="px-4 lg:px-0 flex justify-center sm:justify-start space-x-5">
        <div className="flex items-center">
          <Image
            src={imgInfo.url}
            alt={"Author Featured"}
            priority
            height={30}
            width={30}
            className="align-middle rounded-full"
          />
          <p className="inline align-middle text-gray-700 ml-2 text-lg">
            {yoast.author}
          </p>
        </div>
        <div className="font-medium text-gray-700 flex justify-center items-center gap-x-2">
          <CalenderSVG />{" "}
          <span>{moment(post.date).format("MMM DD, YYYY")}</span>
        </div>
      </div>
      <h1 className="mt-4 mb-8 text-2xl font-semibold text-capitalize">{Parser(post.title.rendered)}</h1>
        <div>
            {Parser(post.content.rendered)}
        </div>
    </div>
  );
}
