/*Template generated by PyCharm on Thursday (9/19/2024), 4:58 AM.
* Author: Kramstyles (USER)
* Filename: PostWidget.jsx
*/

const PostWidget = () => {
    return (
        <div>
            <h1>PostWidget</h1>
        </div>
    );
};

export default PostWidget