/*Template generated by PyCharm on Thursday (9/19/2024), 4:58 AM.
* Author: Kramstyles (USER)
* Filename: PostWidget.jsx
*/

const URL= process.env["NEXT_PUBLIC_PACESETTER_URL"] + "posts?per_page=3";

const PostWidget = async () => {
    const response = await fetch(URL, {
        next: {
            tags: ["posts"],
            revalidate: 6000
        }
    })
    if (!response.ok) throw new Error("Something spoilt during post fetch.");
    const posts = await response.json()
    return (
        <div>
            <h1>PostWidget</h1>
        </div>
    );
};

export default PostWidget