/*Template generated by PyCharm on Saturday (9/21/2024), 6:27 AM.
* Author: Kramstyles (USER)
* Filename: PostDetail.jsx
*/

const PostDetail = () => {
    return (
        <div>
            <h1>PostDetail</h1>
        </div>
    );
};

export default PostDetail