/*Template generated by PyCharm on Saturday (9/21/2024), 6:25 AM.
* Author: Kramstyles (USER)
* Filename: SideBar.jsx
*/

import {Categories, PostWidget} from "@/components/index";

const SideBar = () => {
    return (
        <div className="col-span-1 lg:col-span-4">
          <div className="lg:sticky relative top-10">
            <PostWidget />
            <PostWidget category={1331}/>
            <Categories />
          </div>
        </div>
    );
};

export default SideBar