/*Template generated by NextTSDamn on Sunday (8/25/2024), 2:37 PM.
* Author: Kramstyles (USER)
* Filename: next-ts-tutorial/app/(fetch)/client/page.tsx
*/

const page = () => {
    return (
        <div>
            <h1>page</h1>
        </div>
    );
};

export default page