/*Template generated by google-clone on Saturday (9/7/2024), 12:27 PM.
* Author: Kramstyles (USER)
* Filename: components/CountryLookUp.tsx
*/

const CountryLookUp = () => {
    return (
        <div>
            <h1>CountryLookUp</h1>
        </div>
    );
};

export default CountryLookUp
