/*Template generated by google-clone on Saturday (9/7/2024), 12:27 PM.
 * Author: Kramstyles (USER)
 * Filename: components/CountryLookUp.tsx
 */
"use client";

import { useEffect, useState } from "react";
const API_KEY = process.env["NEXT_PUBLIC_COUNTRY_LOOKUP_API"];

const CountryLookUp = () => {
  const [country, setCountry] = useState("Ghana");
  useEffect(() => {
    const getCountry = async () => {
      const url = `https://extreme-ip-lookup.com/json/?key=${API_KEY}`
      const response = await fetch(url)
        .then((res) => res.json())
        .then((data) => data);
      if (!response) return;

      const details: string = `${response.city}, ${response.country} (${response.countryCode})`
      setCountry(details);
      return;
    };

    getCountry();
  }, []);

  return (
    <div>
      <h1>{country}</h1>
    </div>
  );
};

export default CountryLookUp;
