/*Template generated by google-clone on Sunday (9/15/2024), 4:20 AM.
 * Author: Kramstyles (USER)
 * Filename: components/LoadingImage.tsx
 * animate: spin, ping, pulse, bounce
 */

const LoadingImage = () => {
    return (
        <div className="pt-10 mx-2 lg:pl-52 mx-w-6xl flex sm:space-x-4 flex-col sm:flex-row pb-42">
            <div className="animate-pulse">
                <div className="h-48 w-48 mb-4 bg-gray-200 rounded-md"/>
                <div className="h-2.5 w-48 mb-2.5 bg-gray-200 rounded-md"/>
                <div className="h-4 w-40 mb-4 bg-gray-200 rounded-md"/>
            </div>
            <div className="hidden sm:inline-flex sm:space-x-4">
                <div className="animate-pulse">
                    <div className="h-48 w-48 mb-4 bg-gray-200 rounded-md"/>
                    <div className="h-2 w-48 mb-2.5 bg-gray-200 rounded-md"/>
                    <div className="h-4 w-40 mb-4 bg-gray-200 rounded-md"/>
                </div>
                <div className="animate-pulse">
                    <div className="h-48 w-48 mb-4 bg-gray-200 rounded-md"/>
                    <div className="h-2 w-48 mb-2.5 bg-gray-200 rounded-md"/>
                    <div className="h-4 w-40 mb-4 bg-gray-200 rounded-md"/>
                </div>
                <div className="animate-pulse hidden lg:block">
                    <div className="h-48 w-48 mb-4 bg-gray-200 rounded-md"/>
                    <div className="h-2 w-48 mb-2.5 bg-gray-200 rounded-md"/>
                    <div className="h-4 w-40 mb-4 bg-gray-200 rounded-md"/>
                </div>
            </div>
        </div>
    );
};

export default LoadingImage;
