/*Template generated by google-clone on Sunday (9/15/2024), 1:19 AM.
 * Author: Kramstyles (USER)
 * Filename: components/PaginationButtons.tsx
 */

"use client";

import { usePathname, useSearchParams } from "next/navigation";
import Link from "next/link";
import {TbChevronLeft, TbChevronRight} from "react-icons/tb";

const PaginationButtons = () => {
  const pathname = usePathname();
  const params = useSearchParams();
  const searchTerm = params.get("searchTerm");
  const startIndex = Number(params.get("start")) || 1;

  return (
    <div className="text-blue-700 flex px-10 pb-4 items-center justify-between sm:justify-start sm:px-0 sm:space-x-44">
      {startIndex >= 10 && (
        <Link className="flex space-x-1 items-center hover:underline" href={`${pathname}?searchTerm=${searchTerm}&start=${startIndex - 10}`}>
          <TbChevronLeft className="h-5" /> Previous
        </Link>
      )}

        {startIndex <= 90 && (
        <Link className="flex space-x-1 items-center hover:underline" href={`${pathname}?searchTerm=${searchTerm}&start=${startIndex + 10}`}>
          <TbChevronRight className="h-5" /> Next
        </Link>
      )}
    </div>
  );
};

export default PaginationButtons;
