/*Template generated by google-clone on Wednesday (9/11/2024), 5:06 AM.
 * Author: Kramstyles (USER)
 * Filename: components/SearchBox.tsx
 */

"use client";

import React, { useState } from "react";
import { useSearchParams, useRouter } from "next/navigation";
import SignInOptions from "@/components/SignInOptions";
import { RxCross2 } from "react-icons/rx";
import { TbMicrophone, TbSearch } from "react-icons/tb";

const SearchBox = () => {
  const searchParams = useSearchParams();
  const router = useRouter();
  const searchTerm = searchParams.get("searchTerm");
  const [term, setTerm] = useState<string>(searchTerm || "");

  const pushRouter = (term: string) =>
  {
      if(!term.trim()) return;
      router.push(`/search/web?searchTerm=${term}`);
  }
  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    pushRouter(term);
  };
  return (
    <div className="flex justify-between items-center">
      <form
        onSubmit={handleSubmit}
        className="flex border border-gray-200 rounded-full shadow-lg px-6 py-3 ml-10 mr-5 flex-grow max-w-3xl items-center"
      >
        <input
          type="text"
          className="w-full focus:outline-none"
          value={term}
          onChange={(e) => setTerm(e.target.value)}
        />
        <RxCross2
          className="text-2xl text-gray-500 cursor-pointer sm:mr-2"
          onClick={() => setTerm("")}
        />
        <TbMicrophone className="text-4xl text-blue-500 border-l-2 border-gray-300 cursor-pointer hidden sm:inline-flex mr-3 pl-4" />
        <TbSearch
          className="hidden sm:inline-flex text-2xl text-blue-500 cursor-pointer"
          onClick={() => pushRouter(term)}
        />
      </form>
      <SignInOptions />
    </div>
  );
};

export default SearchBox;
