/*Template generated by google-clone on Wednesday (9/11/2024), 4:30 AM.
* Author: Kramstyles (USER)
* Filename: components/SearchHeader.tsx
*/

const SearchHeader = () => {
    return (
        <div>
            <h1>SearchHeader</h1>
        </div>
    );
};

export default SearchHeader