/*Template generated by google-clone on Saturday (9/14/2024), 12:44 AM.
 * Author: Kramstyles (USER)
 * Filename: components/SearchInput.tsx
 */
"use client";

import { useState } from "react";
// import { useSearchParams } from "next/navigation";

const SearchInput = () => {
  const [term, setTerm] = useState("");
  return (
    <input
      type="text"
      className="w-full focus:outline-none"
      value={term}
      onChange={(e) => setTerm(e.target.value)}
    />
  );
};

export default SearchInput;
