/*Template generated by google-clone on Saturday (9/14/2024), 3:37 AM.
 * Author: Kramstyles (USER)
 * Filename: components/SearchHeaderOptions.tsx
 */
"use client";

import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { TbSearch, TbCameraSearch } from "react-icons/tb";

const SearchHeaderOptions = () => {
  const router = useRouter();
  const searchParam = useSearchParams();
  const searchTerm = searchParam.get("searchTerm");
  const pathname = usePathname();

  const selectTab = (tab: string) => {
    tab = tab === "Images" ? "image" : "web";
    router.push(`/search/${tab}?searchTerm=${searchTerm}`);
  };
  return (
    <div className="flex items-center space-x-2 select-none border-b w-full justify-center lg:justify-start lg:pl-52 text-gray-700 text-sm">
      <div
        onClick={() => selectTab("All")}
        className={`flex items-center space-x-1 border-b-4 border-transparent active:text-blue-500 cursor-pointer pb-3 px-2 ${pathname === "/search/web" && "!text-blue-600 !border-blue-600"}`}
      >
        <TbSearch className="text-md" />
        <p>All</p>
      </div>
      <div
        onClick={() => selectTab("Images")}
        className={`flex items-center space-x-1 border-b-4 border-transparent active:text-blue-500 cursor-pointer pb-3 px-2 ${pathname === "/search/image" && "!text-blue-600 !border-blue-600"}`}
      >
        <TbCameraSearch className="text-md" />
        <p>Images</p>
      </div>
    </div>
  );
};

export default SearchHeaderOptions;
