/*Template generated by google-clone on Wednesday (9/11/2024), 5:06 AM.
* Author: Kramstyles (USER)
* Filename: components/SearchBox.tsx
*/

import SignInOptions from "@/components/SignInOptions";

const SearchBox = () => {
    return (
        <div className="flex justify-between items-center">
            <h1>SearchBox</h1>
            <SignInOptions />
        </div>
    );
};

export default SearchBox