/*Template generated by google-clone on Wednesday (9/11/2024), 5:06 AM.
 * Author: Kramstyles (USER)
 * Filename: components/SearchBox.tsx
 */

import SignInOptions from "@/components/SignInOptions";
import { RxCross2 } from "react-icons/rx";
import { TbMicrophone, TbSearch } from "react-icons/tb";
import SearchInput from "@/components/SearchInput";

const SearchBox = () => {
  return (
    <div className="flex justify-between items-center">
      <form className="flex border border-gray-200 rounded-full shadow-lg px-6 py-3 ml-10 mr-5 flex-grow max-w-3xl items-center">
        <SearchInput />
        <RxCross2 className="text-2xl text-gray-500 cursor-pointer sm:mr-2" />
        <TbMicrophone className="text-4xl text-blue-500 border-l-2 border-gray-300 cursor-pointer hidden sm:inline-flex mr-3 pl-4" />
        <TbSearch className="hidden sm:inline-flex text-2xl text-blue-500 cursor-pointer" />
      </form>
      <SignInOptions />
    </div>
  );
};

export default SearchBox;
