/*Template generated by google-clone on Wednesday (9/11/2024), 5:11 AM.
 * Author: Kramstyles (USER)
 * Filename: components/SignInOptions.tsx
 */

import { TbGridDots, TbSettings } from "react-icons/tb";
import React from "react";

const SignInOptions = () => {
  return (
    <div className="flex space-x-4 items-center">
      <div className="hidden sm:inline-flex">
        <TbSettings className="hover:bg-gray-200 p-2 text-3xl rounded-full cursor-pointer" />
        <TbGridDots className="hover:bg-gray-200 p-2 text-3xl rounded-full cursor-pointer" />
      </div>
      <button className="bg-blue-500 text-white px-6 py-2 font-medium rounded-md hover:brightness-150 hover:shadow-md transition-shadow">
        Sign In
      </button>
    </div>
  );
};

export default SignInOptions;
