/*Template generated by google-clone on Saturday (9/14/2024), 9:10 AM.
 * Author: Kramstyles (USER)
 * Filename: components/WebSearchResult.tsx
 */

import Link from "next/link";
import Parser from "html-react-parser"

export interface ResultProps {
  kind: string;
  title: string;
  htmlTitle: string;
  link: string;
  displayLink: string;
  snippet: string;
  htmlSnippet: string;
  formattedUrl: string;
  htmlFormattedUrl: string;
  image: {contextLink: string}
}
const WebSearchResult = ({ result }: { result: ResultProps }) => {
  return (
    <div className="mb-8 max-w-xl">
      <div className="group flex flex-col">
        <Link href={result.link}>{Parser(result.htmlFormattedUrl)} </Link>
        <Link href={result.link} className="group-hover:underline decoration-blue-800 text-xl truncate font-medium text-blue-800">{result.title}</Link>
      </div>
      <p className="text-gray-600">{Parser(result.htmlSnippet)}</p>
    </div>
  );
};

export default WebSearchResult;
