/*Template generated by PyCharm on Sunday (8/25/2024), 2:34 PM.
* Author: Kramstyles (USER)
* Filename: server/page.tsx
*/

const ServerPage = async () => {
    const url = "https://jsonplaceholder.typicode.com/users";
    const data= await fetch(url, {
        next: {
            revalidate: 300, // Caches and removes cache after 5 Minutes.
        }
    });
    const users =await data.json()
    return (
        <div>
            <h1>Server Data Fetch</h1>
            <ul>
                {users && users?.map((user) => <li key={user.id}>{user.username}, {user.name}</li>)}
            </ul>
        </div>
    );
};

export default ServerPage