/*Template generated by google-clone on Saturday (9/14/2024), 8:44 AM.
* Author: Kramstyles (USER)
* Filename: app/search/error.tsx
*/
"use client"

import React, { useEffect } from "react";
interface ErrorProps {
    error: never;
    reset: () => void;
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
const Error: React.FC<ErrorProps> = ({error, reset}) => {
    useEffect(() => {
        console.log("Error: ", error)
    }, [error]);
    return (
        <div className="flex flex-col justify-center items-center pt-10">
            <h1 className="text-3xl mb-4">Something went wrong!</h1>
            <button className="text-blue-500">Try again!</button>
        </div>
    );
};

export default Error