/*Template generated by NextTSDamn on Thursday (8/29/2024), 1:37 PM.
 * Author: Kramstyles (USER)
 * Filename: next-ts-tutorial/components/DarkModeSwitch.tsx
 */
"use client";

import { AiFillSun, AiFillMoon } from "react-icons/ai";

import { useTheme } from "next-themes";

const DarkModeSwitch = () => {
  const { theme, setTheme, systemTheme } = useTheme();
  // Use the system theme if it is used else use original theme.
  const currentTheme = theme === "system" ? systemTheme : theme;

  return (
    <div>
      {currentTheme === "dark" ? (
        <AiFillSun
          className="text-xl cursor-pointer hover:text-amber-500"
          onClick={() => setTheme("light")}
        />
      ) : (
        <AiFillMoon
          className=" text-xl cursor-pointer hover:text-amber-500"
          onClick={() => setTheme("dark")}
        />
      )}
    </div>
  );
};

export default DarkModeSwitch;
