/*Template generated by NextTSDamn on Monday (8/26/2024), 2:33 PM.
 * Author: Kramstyles (USER)
 * Filename: next-ts-tutorial/app/Header.tsx
 */

import { AiFillHome, AiFillInfoCircle } from "react-icons/ai";

import MenuItem from "@/components/MenuItem";
import Link from "next/link";
const Header = () => {
  return (
    <div className="flex justify-between items-center p-3 mx-auto max-w-6xl ">
      <div className="flex gap-4">
        <MenuItem title={"Home"} address={"/"} Icon={AiFillHome} />
        <MenuItem title={"About"} address={"/about"} Icon={AiFillInfoCircle} />
      </div>
      <Link className="flex gap-1 items-center" href="/">
          <span className="text-2xl font-bold bg-amber-500 py-1 px-2 rounded-lg">IMDB</span>
          <span className="text-xl hidden sm:inline">Clone</span>
      </Link>
    </div>
  );
};

export default Header;
