/*Template generated by NextTSDamn on Tuesday (8/27/2024), 7:59 AM.
 * Author: Kramstyles (USER)
 * Filename: next-ts-tutorial/components/MenuItem.tsx
 */

import React, { ElementType } from "react";
import Link from "next/link";

interface MenuItemProps {
  title: string;
  address: string;
  Icon: ElementType;
}

const MenuItem: React.FC<MenuItemProps> = ({ title, address, Icon }) => {
  return (
    <Link href={address} className="hover:text-amber-500">
      <Icon className="text-2xl sm:hidden" />
      <p className="uppercase hidden sm:inline text-sm">{title}</p>
    </Link>
  );
};

export default MenuItem;
