/*Template generated by NextTSDamn on Thursday (8/29/2024), 2:24 PM.
 * Author: Kramstyles (USER)
 * Filename: next-ts-tutorial/components/NavItem.tsx
 */

"use client";

import React from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";

interface NavItemProps {
  title: string;
  param: string;
}

const NavItem: React.FC<NavItemProps> = ({ title, param }) => {
  const searchParams = useSearchParams();
  const genre = searchParams.get("genre");
  const classes =
    "underline underline-offset-8 decoration-4 decoration-amber-500 dark:decoration-gray-500 rounded-lg";
  return (
    <div
      className={`hover:text-amber-600 dark:hover:text-gray-800 ${genre === param ? classes : ""}`}
    >
      <Link href={`/?genre=${param}`}>{title}</Link>
    </div>
  );
};

export default NavItem;
