/*Template generated by google-clone on Sunday (9/15/2024), 3:54 AM.
 * Author: Kramstyles (USER)
 * Filename: app/search/loading.tsx
 */

import LoadingImage from "@/components/LoadingImage";

const loading = () => {
  return (
    <>
      <LoadingImage />
    </>
  );
};

export default loading;
