import type { Metadata } from "next";
import { cx } from "@/utils";
import { Montserrat, Raleway } from "next/font/google";
import "./globals.css";

const raleway = Raleway({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-raleway",
});
const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cx(
          raleway.variable,
          montserrat.variable,
          "font-raleway bg-light dark:bg-dark",
        )}
      >
        {children}
      </body>
    </html>
  );
}
